### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by geomorillo** [Kingorgg/Nova-Store#2]
![image](https://cloud.githubusercontent.com/assets/295874/17112150/6c060908-526a-11e6-9627-fae2e89c4790.png)

**Comment by geomorillo** [comment]
this is an ajax call so i got onto the url to see the error

**Comment by Kingorgg** [comment]
You need to set up app/Modules/Braintree/Config.php , you can get a free sandbox account here: https://www.braintreepayments.com/en-gb/sandbox and get the API keys, etc.

**Comment by geomorillo** [comment]
oh my :+1:
